### ISSUE TITLE
device-mobus micro service is getting exited after running docker up command

### ISSUE THREAD

**Issue by RoshDevi** [edgexfoundry/demo-grove-pi#3]
I enabled the below micro service in the yaml and tried executing docker up commands and i could observer all the micro services are running except device-mobus micro service, it is getting exited.
Could any one please look into this issue. Thanks in advance.
### #   device-modbus:
#     image: nexus3.edgexfoundry.org:10004/docker-device-modbus:0.6.0
#     ports:
#       - "49991:49991"
#     container_name: edgex-device-modbus
#     networks:
#       - edgex-network
#    volumes:
#      - db-data:/data/db
#      - log-data:/edgex/logs
#      - consul-config:/consul/config
#      - consul-data:/consul/data
#     privileged: true
#     depends_on:
#       - data
#       - command

Note: Iam running the docker on raspberry pi board [contains Ubuntu aarch64 OS]

**Comment by RoshDevi** [comment]
Am using docker-compose-demo-grove.yml in raspberry pi board for running the docker,  device services sucha device-bluetooth , device-snmp,device-modbus , device-mqtt etc are commented in the yml file which means they are not supported???? I tried uncommenting  the modbus-service and tried docker-compose up -d all the service are running successfully except modbus

**Comment by BinduRao2018** [comment]
docker-compose-demo-grove.yml contain services that are required to run device-grove-c service and may not contain the correct configuration of modbus service. To address the service startup issue on modbus, I would suggest you to create an issue on modbus service repository.

**Comment by BinduRao2018** [comment]
@RoshDevi, Could I close this issue as the above mentioned problem should be addressed in another repository?

**Comment by BinduRao2018** [comment]
This ticket will be closed as there is no feedback.
The new release - edinburgh (1.0.1) is  now available for use.
