### ISSUE TITLE
503 Error 

### ISSUE THREAD

**Issue by pgupta408** [edgexfoundry/demo-grove-pi#4]
Hi,

I have tried to follow GrovePi installation steps multiple times and fail to connect to GrovePi with Node-Red properly. 

For GET command of http://10.42.0.1:48082/api/v1/device, I am getting following response:

[{"id":"5ccd24ab9f8fc20001881bde","name":"GroveDevice","adminState":"UNLOCKED","operatingState":"ENABLED","lastConnected":0,"lastReported":0,"labels":["Grove LED, Grove Button, Grove Buzzer, Grove LCD, Grove LightSensor, Grove Relay, Grove RotarySensor, Grove SoundSensor"],"location":null,"commands":[{"created":1556948138545,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd2","name":"Get_ButtonState","get":{"path":"/api/v1/device/{deviceId}/Get_ButtonState","responses":[{"code":"200","description":"valid and accepted","expectedValues":["ButtonState"]},{"code":"503","description":"service unavailable","expectedValues":[]}],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd2"},"put":{"path":null,"responses":null,"parameterNames":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd2"}},{"created":1556948138781,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd3","name":"Get_LightIntensity","get":{"path":"/api/v1/device/{deviceId}/Get_LightIntensity","responses":[{"code":"200","description":"valid and accepted","expectedValues":["LightIntensity"]},{"code":"503","description":"service unavailable","expectedValues":[]}],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd3"},"put":{"path":null,"responses":null,"parameterNames":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd3"}},{"created":1556948138783,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd4","name":"Get_SoundIntensity","get":{"path":"/api/v1/device/{deviceId}/Get_SoundIntensity","responses":[{"code":"200","description":"valid and accepted","expectedValues":["SoundIntensity"]},{"code":"503","description":"service unavailable","expectedValues":[]}],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd4"},"put":{"path":null,"responses":null,"parameterNames":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd4"}},{"created":1556948138785,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd5","name":"Get_RotarySensorMeasurements","get":{"path":"/api/v1/device/{deviceId}/Get_RotarySensorMeasurements","responses":[{"code":"200","description":"valid and accepted","expectedValues":["RotaryAngle","RotaryVoltage"]},{"code":"503","description":"service unavailable","expectedValues":[]}],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd5"},"put":{"path":null,"responses":null,"parameterNames":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd5"}},{"created":1556948138787,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd6","name":"Set_GreenLed","get":{"path":null,"responses":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd6"},"put":{"path":"/api/v1/device/{deviceId}/Set_GreenLed","responses":[{"code":"204","description":"valid and accepted","expectedValues":[]},{"code":"400","description":"bad request","expectedValues":[]},{"code":"503","description":"service unavailable","expectedValues":[]}],"parameterNames":["Green-LED"],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd6"}},{"created":1556948138789,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd7","name":"Set_RedLed","get":{"path":null,"responses":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd7"},"put":{"path":"/api/v1/device/{deviceId}/Set_RedLed","responses":[{"code":"204","description":"valid and accepted","expectedValues":[]},{"code":"400","description":"bad request","expectedValues":[]},{"code":"503","description":"service unavailable","expectedValues":[]}],"parameterNames":["Red-LED"],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd7"}},{"created":1556948138791,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd8","name":"Set_BlueLed","get":{"path":null,"responses":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd8"},"put":{"path":"/api/v1/device/{deviceId}/Set_BlueLed","responses":[{"code":"204","description":"valid and accepted","expectedValues":[]},{"code":"400","description":"bad request","expectedValues":[]},{"code":"503","description":"service unavailable","expectedValues":[]}],"parameterNames":["Blue-LED"],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd8"}},{"created":1556948138793,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bd9","name":"Write_String","get":{"path":null,"responses":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd9"},"put":{"path":"/api/v1/device/{deviceId}/Write_String","responses":[{"code":"204","description":"valid and accepted","expectedValues":[]},{"code":"400","description":"bad request","expectedValues":[]},{"code":"503","description":"service unavailable","expectedValues":[]}],"parameterNames":["Display-String","Row","Column"],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bd9"}},{"created":1556948138795,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bda","name":"Set_Buzzer","get":{"path":null,"responses":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bda"},"put":{"path":"/api/v1/device/{deviceId}/Set_Buzzer","responses":[{"code":"204","description":"valid and accepted","expectedValues":[]},{"code":"400","description":"bad request","expectedValues":[]},{"code":"503","description":"service unavailable","expectedValues":[]}],"parameterNames":["Grove-Buzzer"],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bda"}},{"created":1556948138797,"modified":0,"origin":0,"id":"5ccd24aa9f8fc20001881bdb","name":"Set_Relay","get":{"path":null,"responses":null,"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bdb"},"put":{"path":"/api/v1/device/{deviceId}/Set_Relay","responses":[{"code":"204","description":"valid and accepted","expectedValues":[]},{"code":"400","description":"bad request","expectedValues":[]},{"code":"503","description":"service unavailable","expectedValues":[]}],"parameterNames":["Grove-Relay"],"url":"http://edgex-core-command:48082/api/v1/device/5ccd24ab9f8fc20001881bde/command/5ccd24aa9f8fc20001881bdb"}}]}]

**Comment by BinduRao2018** [comment]
@pgupta408, 
Based on the logs above, the device has been created successfully. Is the problem seen only when the service is used with Node-Red?
Could you provide more information?

**Comment by BinduRao2018** [comment]
@pgupta408,
Do you still see the problem? Can i close this ticket?

**Comment by BinduRao2018** [comment]
Issue closed as there is no feedback.
