### ISSUE TITLE
Is this code slated for edinburgh release?

### ISSUE THREAD

**Issue by jamesrgregg** [edgexfoundry/demo-grove-pi#5]

**Comment by BinduRao2018** [comment]
@jamesrgregg, could you create a branch for edinburgh?
The changes are on master branch as of now.

**Comment by cloudxxx8** [comment]
@SteveOss @iain-anderson do you have permission to create edinburgh branch for this repository?  thanks

**Comment by BinduRao2018** [comment]
Created edinburgh branch and the changes are merged.
